### ISSUE TITLE
Now What....?

### ISSUE THREAD

**Issue by mecizeldec** [RHeijmann/Avorix-Domain-Controller#2]
I've walked through the steps. It's installed. 
Now how do I create users?

I don't have a clue how to operate this in a non-gui environment, and so far have found 0 relevant resources online. 

Help?

**Comment by mecizeldec** [comment]
@RHeijmann are you still working on this?

**Comment by Riktastic** [comment]
Hi @mecizeldec, I'm sorry. Couldn't respond in time.

Users can be created using the default "Active Directory Users and Computers"-program. This is automaticly installed on all editions of Windows Server if the "Active Directory"-role has been installed.

For the normal editions of Windows I currently recommend following this tutorial: https://win10faq.com/active-directory-users-computers-get-use/

It explains the installation and the basic usage of the "Active Directory Users and Computers"-program.

Please could you let me know if this solves your issue. I haven't had a chance to test if the current code works with the latest versions of Raspbian.
